import { WorldCurrency } from "@/components/custom/parameters/currency-combobox";

// ── World currencies (popular, EUR-first) ────────────────────────
export const WORLD_CURRENCIES: WorldCurrency[] = [
  { name: "Euro", code: "EUR", symbol: "€" },
  { name: "US Dollar", code: "USD", symbol: "$" },
  { name: "British Pound", code: "GBP", symbol: "£" },
  { name: "Nigerian Naira", code: "NGN", symbol: "₦" },
  { name: "Japanese Yen", code: "JPY", symbol: "¥" },
  { name: "Swiss Franc", code: "CHF", symbol: "Fr" },
  { name: "Canadian Dollar", code: "CAD", symbol: "CA$" },
  { name: "Australian Dollar", code: "AUD", symbol: "A$" },
  { name: "Chinese Yuan", code: "CNY", symbol: "¥" },
  { name: "Indian Rupee", code: "INR", symbol: "₹" },
  { name: "South Korean Won", code: "KRW", symbol: "₩" },
  { name: "Swedish Krona", code: "SEK", symbol: "kr" },
  { name: "Norwegian Krone", code: "NOK", symbol: "kr" },
  { name: "Danish Krone", code: "DKK", symbol: "kr" },
  { name: "New Zealand Dollar", code: "NZD", symbol: "NZ$" },
  { name: "Singapore Dollar", code: "SGD", symbol: "S$" },
  { name: "Hong Kong Dollar", code: "HKD", symbol: "HK$" },
  { name: "Mexican Peso", code: "MXN", symbol: "MX$" },
  { name: "Brazilian Real", code: "BRL", symbol: "R$" },
  { name: "South African Rand", code: "ZAR", symbol: "R" },
  { name: "UAE Dirham", code: "AED", symbol: "د.إ" },
  { name: "Saudi Riyal", code: "SAR", symbol: "﷼" },
  { name: "Turkish Lira", code: "TRY", symbol: "₺" },
  { name: "Thai Baht", code: "THB", symbol: "฿" },
  { name: "Indonesian Rupiah", code: "IDR", symbol: "Rp" },
  { name: "Malaysian Ringgit", code: "MYR", symbol: "RM" },
  { name: "Philippine Peso", code: "PHP", symbol: "₱" },
  { name: "Pakistani Rupee", code: "PKR", symbol: "₨" },
  { name: "Egyptian Pound", code: "EGP", symbol: "E£" },
  { name: "Russian Ruble", code: "RUB", symbol: "₽" },
  { name: "Polish Złoty", code: "PLN", symbol: "zł" },
  { name: "Czech Koruna", code: "CZK", symbol: "Kč" },
  { name: "Hungarian Forint", code: "HUF", symbol: "Ft" },
  { name: "Ghanaian Cedi", code: "GHS", symbol: "₵" },
  { name: "Kenyan Shilling", code: "KES", symbol: "KSh" },
  { name: "Tanzanian Shilling", code: "TZS", symbol: "TSh" },
  { name: "Ugandan Shilling", code: "UGX", symbol: "USh" },
  { name: "Moroccan Dirham", code: "MAD", symbol: "MAD" },
  { name: "West African CFA Franc", code: "XOF", symbol: "CFA" },
  { name: "Central African CFA Franc", code: "XAF", symbol: "FCFA" },
  { name: "Qatari Riyal", code: "QAR", symbol: "QR" },
  { name: "Kuwaiti Dinar", code: "KWD", symbol: "KD" },
  { name: "Bahraini Dinar", code: "BHD", symbol: "BD" },
];

export const ipoTemplateFields = [
  "subscriberName",
  "accountNumber",
  "chn",
  "units",
  "amount",
  "remark",
];
