import { WorldCurrency } from "@/components/custom/parameters/currency-combobox";

// â”€â”€ World currencies (popular, EUR-first) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
export const WORLD_CURRENCIES: WorldCurrency[] = [
  { name: "Euro", code: "EUR", symbol: "â‚¬" },
  { name: "US Dollar", code: "USD", symbol: "$" },
  { name: "British Pound", code: "GBP", symbol: "Â£" },
  { name: "Nigerian Naira", code: "NGN", symbol: "â‚¦" },
  { name: "Japanese Yen", code: "JPY", symbol: "Â¥" },
  { name: "Swiss Franc", code: "CHF", symbol: "Fr" },
  { name: "Canadian Dollar", code: "CAD", symbol: "CA$" },
  { name: "Australian Dollar", code: "AUD", symbol: "A$" },
  { name: "Chinese Yuan", code: "CNY", symbol: "Â¥" },
  { name: "Indian Rupee", code: "INR", symbol: "â‚¹" },
  { name: "South Korean Won", code: "KRW", symbol: "â‚©" },
  { name: "Swedish Krona", code: "SEK", symbol: "kr" },
  { name: "Norwegian Krone", code: "NOK", symbol: "kr" },
  { name: "Danish Krone", code: "DKK", symbol: "kr" },
  { name: "New Zealand Dollar", code: "NZD", symbol: "NZ$" },
  { name: "Singapore Dollar", code: "SGD", symbol: "S$" },
  { name: "Hong Kong Dollar", code: "HKD", symbol: "HK$" },
  { name: "Mexican Peso", code: "MXN", symbol: "MX$" },
  { name: "Brazilian Real", code: "BRL", symbol: "R$" },
  { name: "South African Rand", code: "ZAR", symbol: "R" },
  { name: "UAE Dirham", code: "AED", symbol: "Ø¯.Ø¥" },
  { name: "Saudi Riyal", code: "SAR", symbol: "ï·¼" },
  { name: "Turkish Lira", code: "TRY", symbol: "â‚º" },
  { name: "Thai Baht", code: "THB", symbol: "à¸¿" },
  { name: "Indonesian Rupiah", code: "IDR", symbol: "Rp" },
  { name: "Malaysian Ringgit", code: "MYR", symbol: "RM" },
  { name: "Philippine Peso", code: "PHP", symbol: "â‚±" },
  { name: "Pakistani Rupee", code: "PKR", symbol: "â‚¨" },
  { name: "Egyptian Pound", code: "EGP", symbol: "EÂ£" },
  { name: "Russian Ruble", code: "RUB", symbol: "â‚½" },
  { name: "Polish ZÅ‚oty", code: "PLN", symbol: "zÅ‚" },
  { name: "Czech Koruna", code: "CZK", symbol: "KÄ" },
  { name: "Hungarian Forint", code: "HUF", symbol: "Ft" },
  { name: "Ghanaian Cedi", code: "GHS", symbol: "â‚µ" },
  { name: "Kenyan Shilling", code: "KES", symbol: "KSh" },
  { name: "Tanzanian Shilling", code: "TZS", symbol: "TSh" },
  { name: "Ugandan Shilling", code: "UGX", symbol: "USh" },
  { name: "Moroccan Dirham", code: "MAD", symbol: "MAD" },
  { name: "West African CFA Franc", code: "XOF", symbol: "CFA" },
  { name: "Central African CFA Franc", code: "XAF", symbol: "FCFA" },
  { name: "Qatari Riyal", code: "QAR", symbol: "QR" },
  { name: "Kuwaiti Dinar", code: "KWD", symbol: "KD" },
  { name: "Bahraini Dinar", code: "BHD", symbol: "BD" },
];

export const ipoTemplateFields = [
  "subscriberName",
  "accountNumber",
  "chn",
  "broker",
  "bank",
  "state",
  "stockbrokerCode",
  "certNo",
  "cscsAccountNo",
  "symbol",
  "units",
  "amount",
  "remark",
];

export const allottmentTemplateFields = [
  "SHAREHOLDER NAME",
  "CHN",
  "STOCKBROKER CODE",
  "UNITS HELD",
  "RIGHTS DUE",
  "ADDITIONAL CERTIFICATE",
  "BANK NAME",
  "ACCOUNT NO",
  "AMOUNT TO RETURN",
  "REASON",
];

export const RIGHTS_REPORT_TYPES = [
  "Rights Entitlement List",
  "Acceptance Summary",
  "Non-Acceptance List",
  "Traded Rights Report",
  "Allotment Report",
  "State Analysis",
  "Range Analysis",
];

export const REPORT_TYPES = [
  "Application Offer",
  "Application Offer Summary",
  "Full Subscription List",
  "State Summary",
  "Range Analysis",
  "Summary Batch Report",
];

// â”€â”€ Types ------â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

type AddressRecord = {
  id: string;
  register: string;
  registerName: string;
  chn: string;
  accountNo: string;
  holderName: string;
  phone: string;
  email: string;
  address: string; // new CSCS address â€” always replaces old
  detectedState: string; // GIS-inferred state for tax jurisdiction
  confirmedState: string | null; // null = unconfirmed
};

// â”€â”€ Mock data ------â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

export const INITIAL_RECORDS: AddressRecord[] = [
  {
    id: "r1",
    register: "DANGCEM",
    registerName: "Dangote Cement Plc",
    chn: "C00002198KL",
    accountNo: "DANGCEM-10044",
    holderName: "Chukwuemeka Obi",
    phone: "08031234567",
    email: "c.obi@email.com",
    address: "45 Aminu Kano Crescent, Wuse 2",
    detectedState: "Abuja (FCT)",
    confirmedState: null,
  },
  {
    id: "r2",
    register: "DANGCEM",
    registerName: "Dangote Cement Plc",
    chn: "C00003312MN",
    accountNo: "DANGCEM-10091",
    holderName: "Fatima Aliyu",
    phone: "07059876543",
    email: "f.aliyu@email.com",
    address: "7 Ahmadu Bello Way, Kaduna South",
    detectedState: "Kaduna",
    confirmedState: null,
  },
  {
    id: "r3",
    register: "DANGCEM",
    registerName: "Dangote Cement Plc",
    chn: "C00005023RT",
    accountNo: "DANGCEM-10109",
    holderName: "Yusuf Mohammed",
    phone: "08098765432",
    email: "y.mohammed@mail.com",
    address: "Plot 3 Ibrahim Taiwo Road, Nassarawa",
    detectedState: "Kano",
    confirmedState: null,
  },
  {
    id: "r4",
    register: "DANGCEM",
    registerName: "Dangote Cement Plc",
    chn: "C00006112BC",
    accountNo: "DANGCEM-10158",
    holderName: "Halima Yusuf",
    phone: "08123456789",
    email: "h.yusuf@company.ng",
    address: "14 Shehu Shagari Way, Minna",
    detectedState: "Niger",
    confirmedState: null,
  },
  {
    id: "r5",
    register: "ZENITHBANK",
    registerName: "Zenith Bank Plc",
    chn: "C00008821AB",
    accountNo: "ZENITHBANK-20033",
    holderName: "Adaeze Nwosu",
    phone: "08122334455",
    email: "adaeze.n@gmail.com",
    address: "14 Marina Street, Lagos Island",
    detectedState: "Lagos",
    confirmedState: null,
  },
  {
    id: "r6",
    register: "ZENITHBANK",
    registerName: "Zenith Bank Plc",
    chn: "C00009102XY",
    accountNo: "ZENITHBANK-20081",
    holderName: "Emeka Eze",
    phone: "07033221144",
    email: "emeka.e@yahoo.com",
    address: "22 New GRA, Trans Amadi",
    detectedState: "Rivers",
    confirmedState: null,
  },
  {
    id: "r7",
    register: "ZENITHBANK",
    registerName: "Zenith Bank Plc",
    chn: "C00010344PQ",
    accountNo: "ZENITHBANK-20102",
    holderName: "Tunde Adeyemi",
    phone: "09011223344",
    email: "t.adeyemi@mail.com",
    address: "3 Obafemi Awolowo Road, Alausa, Ikeja",
    detectedState: "Lagos",
    confirmedState: null,
  },
  {
    id: "r8",
    register: "ACCESSCORP",
    registerName: "Access Holdings Plc",
    chn: "C00011299PQ",
    accountNo: "ACCESSCORP-30017",
    holderName: "Ngozi Okafor",
    phone: "09012344321",
    email: "n.okafor@company.ng",
    address: "Plot 999 Danmole Street, Victoria Island",
    detectedState: "Lagos",
    confirmedState: null,
  },
  {
    id: "r9",
    register: "ACCESSCORP",
    registerName: "Access Holdings Plc",
    chn: "C00012580RS",
    accountNo: "ACCESSCORP-30044",
    holderName: "Uche Okeke",
    phone: "08077889900",
    email: "u.okeke@firm.ng",
    address: "18 Douglas Road, Owerri",
    detectedState: "Imo",
    confirmedState: null,
  },
  {
    id: "r10",
    register: "GTCO",
    registerName: "GTCO Holdings Plc",
    chn: "C00015001ZA",
    accountNo: "GTCO-40011",
    holderName: "Bello Musa",
    phone: "07022334455",
    email: "b.musa@email.com",
    address: "5 Paiko Road, Minna",
    detectedState: "Niger",
    confirmedState: null,
  },
  {
    id: "r11",
    register: "GTCO",
    registerName: "GTCO Holdings Plc",
    chn: "C00015894TW",
    accountNo: "GTCO-40039",
    holderName: "Chioma Ike",
    phone: "08166778899",
    email: "chioma.i@gmail.com",
    address: "22 Ogui Road, Enugu",
    detectedState: "Enugu",
    confirmedState: null,
  },
  {
    id: "r12",
    register: "GTCO",
    registerName: "GTCO Holdings Plc",
    chn: "C00016230WX",
    accountNo: "GTCO-40067",
    holderName: "Suleiman Garba",
    phone: "07099887766",
    email: "s.garba@kano.ng",
    address: "Plot 44 Ibrahim Taiwo Road",
    detectedState: "Kano",
    confirmedState: null,
  },
];

export const PROCESSING_STAGES: [number, string][] = [
  [15, "Verifying ZIP integrityâ€¦"],
  [30, "Extracting register dataâ€¦"],
  [50, "Parsing shareholder recordsâ€¦"],
  [70, "Running GIS state detectionâ€¦"],
  [90, "Grouping by registerâ€¦"],
  [100, "Ready for review"],
];
